[packaging]
package_name = "azure-mgmt-workloads-sapvirtualinstance"
package_nspkg = "azure-mgmt-workloads-nspkg"
package_pprint_name = "MyService Management"
package_doc_id = ""
is_stable = false
is_arm = true
need_msrestazure = false
need_azuremgmtcore = true
sample_link = ""
exclude_folders = ""
